FROM --platform=$BUILDPLATFORM docker.io/golang:1.22@sha256:0ca97f4ab335f4b284a5b8190980c7cdc21d320d529f2b643e8a8733a69bfb6b as build

ARG TARGETOS
ARG TARGETARCH

ADD . /src
WORKDIR /src

RUN make build

FROM docker.io/python:3.12-alpine@sha256:38e179a0f0436c97ecc76bcd378d7293ab3ee79e4b8c440fdc7113670cb6e204

LABEL maintainer="ownCloud DevOps <devops@owncloud.com>"
LABEL org.opencontainers.image.authors="ownCloud DevOps <devops@owncloud.com>"
LABEL org.opencontainers.image.title="drone-ansible"
LABEL org.opencontainers.image.url="https://github.com/owncloud-ci/drone-ansible"
LABEL org.opencontainers.image.source="https://github.com/owncloud-ci/drone-ansible"
LABEL org.opencontainers.image.documentation="https://github.com/owncloud-ci/drone-ansible"

ARG TARGETOS
ARG TARGETARCH
ARG ANSIBLE_VERSION

# renovate: datasource=pypi depName=ansible
ENV ANSIBLE_VERSION="${ANSIBLE_VERSION:-9.5.1}"

RUN apk --update add --virtual .build-deps python3-dev libffi-dev build-base && \
    apk add --no-cache bash git curl rsync openssh-client sshpass && \
    apk upgrade --no-cache libcrypto3 libssl3 libexpat && \
    pip install -qq --no-cache-dir --upgrade pip && \
    pip install -qq --no-cache-dir ansible=="${ANSIBLE_VERSION}" \
      boto3 hcloud pywinrm passlib jsonschema && \
    apk del .build-deps && \
    rm -rf /var/cache/apk/* && \
    rm -rf /tmp/* && \
    rm -rf /root/.cache/

COPY --from=build /src/dist/drone-ansible /bin/drone-ansible
ENTRYPOINT ["/bin/drone-ansible"]
