FROM plugins/base:linux-arm@sha256:186ca996404622ab931059474268acee0ffd64dcbf163b8a7385111f1c51af49

LABEL maintainer="ownCloud DevOps <devops@owncloud.com>"
LABEL org.opencontainers.image.authors="ownCloud DevOps <devops@owncloud.com>"
LABEL org.opencontainers.image.title="drone-ansible"
LABEL org.opencontainers.image.url="https://github.com/owncloud-ci/drone-ansible"
LABEL org.opencontainers.image.source="https://github.com/owncloud-ci/drone-ansible"
LABEL org.opencontainers.image.documentation="https://github.com/owncloud-ci/drone-ansible"

ARG ANSIBLE_VERSION

# renovate: datasource=pypi depName=ansible
ENV ANSIBLE_VERSION="${ANSIBLE_VERSION:-2.10.6}"

RUN apk add --no-cache bash git curl rsync openssh-client sshpass py3-pip py3-requests py3-paramiko python3-dev libffi-dev libressl-dev libressl build-base && \
  pip3 install -U pip && \
  pip3 install ansible=="${ANSIBLE_VERSION}" boto3 hcloud && \
  apk del --no-cache python3-dev libffi-dev libressl-dev build-base

ADD release/linux/arm/drone-ansible /bin/
ENTRYPOINT ["/bin/drone-ansible"]
