FROM arm64v8/alpine:3.13@sha256:071fa5de01a240dbef5be09d69f8fef2f89d68445d9175393773ee389b6f5935

LABEL maintainer="ownCloud DevOps <devops@owncloud.com>"
LABEL org.opencontainers.image.authors="ownCloud DevOps <devops@owncloud.com>"
LABEL org.opencontainers.image.title="drone-ansible"
LABEL org.opencontainers.image.url="https://github.com/owncloud-ci/drone-ansible"
LABEL org.opencontainers.image.source="https://github.com/owncloud-ci/drone-ansible"
LABEL org.opencontainers.image.documentation="https://github.com/owncloud-ci/drone-ansible"

ARG ANSIBLE_VERSION

# renovate: datasource=pypi depName=ansible
ENV ANSIBLE_VERSION="${ANSIBLE_VERSION:-3.1.0}"

RUN apk add --no-cache bash git curl rsync openssh-client sshpass py3-pip py3-requests py3-paramiko python3-dev libffi-dev libressl-dev libressl build-base && \
  pip3 install -U pip && \
  pip3 install ansible=="${ANSIBLE_VERSION}" boto3 hcloud && \
  apk del --no-cache python3-dev libffi-dev libressl-dev build-base

ADD release/linux/arm64/drone-ansible /bin/
ENTRYPOINT ["/bin/drone-ansible"]
